use_frameworks!

target 'ZWIdcardKeyboard_Example' do
  pod 'ZWIdcardKeyboard', :path => '../'

  target 'ZWIdcardKeyboard_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
